{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "System - Dev",
   "type": "gauge",
   "description": "Measures memory usage and CPU usage for dev.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "MEMORY USAGE"
    },
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU USAGE"
    }
   ]
  },
  {
   "title": "System - Prd",
   "type": "gauge",
   "description": "Measures memory usage and CPU usage for prd.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "MEMORY USAGE"
    },
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU USAGE"
    }
   ]
  },
  {
   "title": "Requests - Dev",
   "type": "timeseries",
   "description": "Keeps track of all development requests being made.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests - Prd",
   "type": "timeseries",
   "description": "Keeps track of all production requests being made.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[30s])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Latency - Dev",
   "type": "timeseries",
   "description": "Keeps track of the average latency per development request",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "request_latency_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Request Latency - Prd",
   "type": "timeseries",
   "description": "Keeps track of the average latency per production request",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "request_latency_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Latency - Dev",
   "type": "timeseries",
   "description": "Keeps track of the average latency per development pizza creation request",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_latency_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "Pizza Latency - Prd",
   "type": "timeseries",
   "description": "Keeps track of the average latency per production pizza creation request",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_latency_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "Active Users - Dev",
   "type": "timeseries",
   "description": "Keeps track of the number of active users in the development environment.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Active Users - Prd",
   "type": "timeseries",
   "description": "Keeps track of the number of active users in the production environment.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Auth Requests - Dev",
   "type": "timeseries",
   "description": "Keeps track of successful and failing development auth requests",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(auth_successes_per_min_total{source=\"jwt-pizza-service-dev\"}[1m])*60",
     "legendFormat": "Auth Request Successes"
    },
    {
     "expr": "rate(auth_failures_per_min_total{source=\"jwt-pizza-service-dev\"}[1m]) * 60",
     "legendFormat": "Auth Request Failures"
    }
   ]
  },
  {
   "title": "Auth Requests - Prd",
   "type": "timeseries",
   "description": "Keeps track of successful and failing production auth requests",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 40 },
   "targets": [
    {
     "expr": "rate(auth_successes_per_min_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Auth Request Successes"
    },
    {
     "expr": "rate(auth_failures_per_min_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Auth Request Failures"
    }
   ]
  },
  {
   "title": "Pizzas - Dev",
   "type": "timeseries",
   "description": "Keeps track of development pizzas sold and pizza creation failures.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service-dev\"}[1m])*60",
     "legendFormat": "Pizzas Sold / Minute"
    },
    {
     "expr": "pizza_creation_failures_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza Creation Failures"
    }
   ]
  },
  {
   "title": "Pizzas - Prd",
   "type": "timeseries",
   "description": "Keeps track of production pizzas sold and pizza creation failures.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 48 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Pizzas Sold / Minute"
    },
    {
     "expr": "pizza_creation_failures_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Failures"
    }
   ]
  },
  {
   "title": "Revenue - Dev",
   "type": "stat",
   "description": "Keeps track of BTC gain per minute in development",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_BTC_total{source=\"jwt-pizza-service-dev\"}[1m])*60",
     "legendFormat": "BTC/Min"
    }
   ]
  },
  {
   "title": "Revenue - Prd",
   "type": "stat",
   "description": "Keeps track of BTC gain per minute in production",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_BTC_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "BTC/Min"
    }
   ]
  }
 ]
}